version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: planex-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: planex-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: planex-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_next:/app/.next
    restart: unless-stopped
volumes:
  frontend_next: 
