export function downloadFile(filename: string, content: string, mimeType: string = "text/plain") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateMarkdownBlueprint(
  projectName: string,
  sections: {
    idea?: any;
    database?: any;
    api?: any;
    folder?: any;
  }
): string {
  const { idea, database, api, folder } = sections;

  let md = `# ${projectName} — System Architecture Blueprint\n\n`;
  md += `> Generated by **Planex Architecture Engine** on ${new Date().toLocaleDateString()}\n\n`;
  md += `---\n\n`;

  // 1. Executive Summary & Ideation
  md += `## 1. System Overview & Ideation\n\n`;
  if (idea) {
    if (idea.raw_idea) md += `**Core Concept:**\n> ${idea.raw_idea}\n\n`;
    if (idea.overview) md += `**Overview:**\n${idea.overview}\n\n`;
    if (idea.estimated_complexity) md += `**Estimated Complexity:** \`${idea.estimated_complexity.toUpperCase()}\`\n\n`;
    if (idea.team_size) md += `**Target Team Size:** ${idea.team_size}\n\n`;

    if (Array.isArray(idea.key_features) && idea.key_features.length > 0) {
      md += `### Key Features\n\n`;
      idea.key_features.forEach((f: any, i: number) => {
        md += `${i + 1}. **${f.name}** (${f.priority === "must_have" ? "Must Have" : "Nice to Have"})\n   ${f.description}\n\n`;
      });
    }

    if (idea.suggested_tech_stack) {
      md += `### Suggested Technology Stack\n\n`;
      const stack = idea.suggested_tech_stack;
      if (stack.frontend?.length) md += `- **Frontend:** ${stack.frontend.join(", ")}\n`;
      if (stack.backend?.length) md += `- **Backend:** ${stack.backend.join(", ")}\n`;
      if (stack.database?.length) md += `- **Database:** ${stack.database.join(", ")}\n`;
      if (stack.infrastructure?.length) md += `- **Infrastructure & Cloud:** ${stack.infrastructure.join(", ")}\n`;
      if (stack.ai?.length) md += `- **AI & Machine Learning:** ${stack.ai.join(", ")}\n`;
      if (stack.frameworks?.length) md += `- **Libraries & Frameworks:** ${stack.frameworks.join(", ")}\n`;
      md += `\n`;
    }
  } else {
    md += `*No idea section data recorded yet.*\n\n`;
  }

  md += `---\n\n`;

  // 2. Database Architecture
  md += `## 2. Database Schema & Data Models\n\n`;
  if (database && Array.isArray(database.entities) && database.entities.length > 0) {
    database.entities.forEach((entity: any) => {
      md += `### Entity: \`${entity.name}\`\n`;
      if (entity.description) md += `${entity.description}\n\n`;

      if (Array.isArray(entity.fields) && entity.fields.length > 0) {
        md += `| Field | Type | Required | Unique | Description |\n`;
        md += `|-------|------|----------|--------|-------------|\n`;
        entity.fields.forEach((field: any) => {
          md += `| \`${field.name}\` | \`${field.type}\` | ${field.required ? "Yes" : "No"} | ${field.unique ? "Yes" : "No"} | ${field.description || "-"} |\n`;
        });
        md += `\n`;
      }
    });

    if (Array.isArray(database.relationships) && database.relationships.length > 0) {
      md += `### Entity Relationships\n\n`;
      database.relationships.forEach((rel: any) => {
        md += `- **${rel.from}** $\\rightarrow$ **${rel.to}** (\`${rel.type}\`): ${rel.description || ""}\n`;
      });
      md += `\n`;
    }
  } else {
    md += `*No database schema configured yet.*\n\n`;
  }

  md += `---\n\n`;

  // 3. API Architecture
  md += `## 3. API & WebSockets Specification\n\n`;
  if (api) {
    if (api.auth) {
      md += `### Authentication Protocol\n`;
      md += `- **Type:** \`${api.auth.type}\`\n`;
      md += `- **Details:** ${api.auth.description}\n`;
      if (api.auth.routes?.length) md += `- **Protected Routes:** ${api.auth.routes.map((r: string) => `\`${r}\``).join(", ")}\n`;
      md += `\n`;
    }

    if (Array.isArray(api.rest) && api.rest.length > 0) {
      md += `### REST Endpoints (${api.rest.length} routes)\n\n`;
      api.rest.forEach((route: any) => {
        md += `#### \`${route.method} ${route.path}\` — ${route.name}\n`;
        md += `${route.description}\n\n`;
        md += `- **Auth Required:** ${route.authRequired ? "🔒 Yes" : "🔓 No"}\n`;
        if (route.request?.body && Object.keys(route.request.body).length > 0) {
          md += `- **Request Body:** \`\`\`json\n${JSON.stringify(route.request.body, null, 2)}\n\`\`\`\n`;
        }
        if (route.response?.success) {
          md += `- **Response Schema:** \`\`\`json\n${JSON.stringify(route.response.success, null, 2)}\n\`\`\`\n`;
        }
        md += `\n`;
      });
    }

    if (Array.isArray(api.realtime) && api.realtime.length > 0) {
      md += `### Realtime WebSocket Events\n\n`;
      api.realtime.forEach((ev: any) => {
        md += `- **\`${ev.name}\`**: ${ev.description}\n`;
      });
      md += `\n`;
    }
  } else {
    md += `*No API specification recorded yet.*\n\n`;
  }

  md += `---\n\n`;

  // 4. Folder Structure
  md += `## 4. Directory & Folder Architecture\n\n`;
  if (folder && Array.isArray(folder.root)) {
    md += `\`\`\`text\n`;
    const formatTree = (nodes: any[], prefix = ""): string => {
      let out = "";
      nodes.forEach((node: any, idx: number) => {
        const isLast = idx === nodes.length - 1;
        const pointer = isLast ? "└── " : "├── ";
        out += `${prefix}${pointer}${node.name}${node.type === "folder" ? "/" : ""}\n`;
        if (node.children && node.children.length > 0) {
          out += formatTree(node.children, prefix + (isLast ? "    " : "│   "));
        }
      });
      return out;
    };
    md += `${projectName}/\n`;
    md += formatTree(folder.root);
    md += `\`\`\`\n\n`;
  } else {
    md += `*No directory structure defined yet.*\n\n`;
  }

  md += `---\n*Generated with Planex — The AI Software Architecture Engine*\n`;
  return md;
}

export function generateSqlSchema(database: any): string {
  if (!database || !Array.isArray(database.entities) || database.entities.length === 0) {
    return "-- No database entities defined yet\n";
  }

  let sql = `-- PostgreSQL Schema generated by Planex\n-- Date: ${new Date().toISOString()}\n\n`;
  sql += `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n`;

  database.entities.forEach((entity: any) => {
    const tableName = entity.name.toLowerCase().replace(/\s+/g, "_");
    sql += `CREATE TABLE IF NOT EXISTS "${tableName}" (\n`;

    const fieldDefs: string[] = [];
    if (Array.isArray(entity.fields)) {
      entity.fields.forEach((field: any) => {
        const fieldName = field.name.toLowerCase().replace(/\s+/g, "_");
        let fieldType = "TEXT";
        const t = String(field.type).toLowerCase();

        if (t.includes("uuid") || t.includes("id")) fieldType = "UUID DEFAULT uuid_generate_v4()";
        else if (t.includes("int") || t.includes("number")) fieldType = "INTEGER";
        else if (t.includes("bool")) fieldType = "BOOLEAN";
        else if (t.includes("date") || t.includes("time")) fieldType = "TIMESTAMP WITH TIME ZONE DEFAULT NOW()";
        else if (t.includes("json")) fieldType = "JSONB";
        else if (t.includes("float") || t.includes("decimal")) fieldType = "NUMERIC(10,2)";

        let def = `  "${fieldName}" ${fieldType}`;
        if (field.name.toLowerCase() === "id") def += " PRIMARY KEY";
        if (field.required && field.name.toLowerCase() !== "id") def += " NOT NULL";
        if (field.unique && field.name.toLowerCase() !== "id") def += " UNIQUE";

        fieldDefs.push(def);
      });
    }

    sql += fieldDefs.join(",\n");
    sql += `\n);\n\n`;

    if (entity.description) {
      sql += `COMMENT ON TABLE "${tableName}" IS '${entity.description.replace(/'/g, "''")}';\n\n`;
    }
  });

  return sql;
}
